[package]
name = "snake_3d_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snake_3d_engine = { path = "../snake_3d_engine" }
futures = "0.3.30"
